workflows:
  ios-release-workflow:
    name: iOS Release Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    integrations:
      app_store_connect:
        api_key: $API_KEYS
        key_id: 7YVW5HR78A
        issuer_id: 373dae42-6ed9-4b2f-b003-64582bc4c3a0

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build iOS release
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.ipa

    publishing:
      app_store_connect:
        auth: integration  # Utilise l'intégration pour App Store Connect
        submit_to_testflight: true
